SELECT PJ.PRODUCT_CODE, SUM(RESULT) AS SALES
FROM
(
    SELECT P.PRODUCT_CODE, PRICE, SALES_AMOUNT, (PRICE*SALES_AMOUNT) AS RESULT
    FROM PRODUCT P JOIN OFFLINE_SALE OS ON P.PRODUCT_ID = OS.PRODUCT_ID
) PJ
GROUP BY PJ.PRODUCT_CODE
ORDER BY SALES DESC, PJ.PRODUCT_CODE;