SELECT CR.CAR_ID, CR.CAR_TYPE, ROUND((CR.DAILY_FEE*30)*(100-CP.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CR 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP 
ON CR.CAR_TYPE = CP.CAR_TYPE

WHERE CP.DURATION_TYPE = '30일 이상' 
AND CR.CAR_TYPE IN('세단', 'SUV') 
AND NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
    WHERE CH.CAR_ID = CR.CAR_ID
    AND CH.END_DATE > TO_DATE('2022-11-01', 'YYYY-MM-DD') 
    AND CH.START_DATE < TO_DATE('2022-12-01', 'YYYY-MM-DD')
) 
AND ROUND(CR.DAILY_FEE*30*(100-CP.DISCOUNT_RATE)/100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC