-- SELECT AI.NAME, AI.DATETIME 
-- FROM ANIMAL_INS AI LEFT OUTER JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
-- WHERE AO.DATETIME IS NULL
-- ORDER BY AI.DATETIME 
-- LIMIT 3;

SELECT NAME, DATETIME FROM ANIMAL_INS 
WHERE NOT EXISTS (SELECT ANIMAL_ID FROM ANIMAL_OUTS WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID) 
ORDER BY DATETIME FETCH FIRST 3 ROWS ONLY;