-- 코드를 입력하세요

-- SELECT * FROM ANIMAL_INS AI JOIN ANIMAL_OUTS AO USING (ANIMAL_ID)
--     WHERE AO.DATETIME < AI.DATETIME;

-- SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE ANIMAL_ID = 
SELECT AI.ANIMAL_ID	, AI.NAME FROM ANIMAL_INS AI JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME < AI.DATETIME ORDER BY AI.DATETIME;