-- 코드를 작성해주세요
# SELECT DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') AS YEAR, 
# ((SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA GROUP BY DIFFERENTIATION_DATE) - SIZE_OF_COLONY) AS YEAR_DEV, 
# ID FROM ECOLI_DATA
# ORDER BY YEAR, YEAR_DEV;

SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, 
(SELECT M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, 
ID 
FROM ECOLI_DATA E
JOIN  (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE FROM ECOLI_DATA GROUP BY YEAR
      ) M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV;

# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE FROM ECOLI_DATA GROUP BY YEAR;